CCDNComponent\AttachmentBundle\Entity\Attachment:
    type: entity
    table: cc_component_attachment
    repositoryClass: CCDNComponent\AttachmentBundle\Repository\AttachmentRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        createdDate:
            type: datetime
            column: created_date
        description:
            type: text
            nullable: true
        filenameOriginal:
            type: string
            column: file_name_original
            nullable: true
        publicKey:
            type: string
            column: public_hash_key
            nullable: true
        privateKey:
            type: string
            column: private_hash_key
            nullable: true
        fileExtension:
            type: string
            column: file_extension
            nullable: true
        fileSize:
            type: string
            column: file_size
            nullable: true
    manyToOne:
        ownedByUser:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            #cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_owned_by_user_id
                referencedColumnName: id
                onDelete: SET NULL
