CCDNComponent\AttachmentBundle\Entity\Attachment:
    type: entity
    table: CC_Component_Attachment
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        createdDate:
            name: "created_date"
            type: datetime
        description:
            type: text
            nullable: true
        filenameOriginal:
            type: string
            name: "file_name_original"
            nullable: true
        filenameHashed:
            type: string
            name: "file_name_hashed"
            nullable: true
        fileExtension:
            type: string
            name: "file_extension"
            nullable: true
        fileSize:
            type: string
            name: "file_size"
            nullable: true
    manyToOne:
        ownedBy:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            #cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_owned_by_user_id
                referencedColumnName: id
                onDelete: SET NULL
