ccdn_component_attachment_index:
    pattern: /{_locale}/attachments
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:index, _locale: en, page: 0, userId: 0 }

ccdn_component_attachment_index_paginated:
    pattern: /{_locale}/attachments/page/{page}
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:index, _locale: en, page: 0, userId: 0 }

ccdn_component_attachment_for_user:
    pattern: /{_locale}/attachments/for/user/{userId}
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:index, _locale: en, page: 0, userId: 0 }

ccdn_component_attachment_for_user_paginated:
    pattern: /{_locale}/attachments/for/user/{userId}/page/{page}
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:index, _locale: en, page: 0, userId: 0 }

ccdn_component_attachment_upload:
    pattern: /{_locale}/attachment/upload
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:upload, _locale: en }

ccdn_component_attachment_thumbnail:
    pattern: /{_locale}/attachment/{attachmentId}/thumbnail
    defaults: { _controller: CCDNComponentAttachmentBundle:Retriever:thumbnail, _locale: en }

ccdn_component_attachment_download:
    pattern: /{_locale}/attachment/{attachmentId}/download
    defaults: { _controller: CCDNComponentAttachmentBundle:Retriever:download, _locale: en }

ccdn_component_attachment_bulk_action:
    pattern: /{_locale}/attachment/action/checked
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:bulk, _locale: en }
