ccdn_component_attachment_index:
    pattern: /{_locale}/attachments
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:index, _locale: en }

ccdn_component_attachment_upload:
    pattern: /{_locale}/attachment/upload
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:upload, _locale: en }

ccdn_component_attachment_thumbnail:
    pattern: /{_locale}/attachment/thumbnail/{scale}/{publicKey}
    defaults: { _controller: CCDNComponentAttachmentBundle:Retriever:thumbnail, _locale: en, scale: 20 }

ccdn_component_attachment_download:
    pattern: /{_locale}/attachment/download/{publicKey}
    defaults: { _controller: CCDNComponentAttachmentBundle:Retriever:download, _locale: en }

ccdn_component_attachment_bulk_action:
    pattern: /{_locale}/attachment/action/checked
    defaults: { _controller: CCDNComponentAttachmentBundle:Manage:bulk, _locale: en }
