parameters:

    # Service Parameters defined in app/config
    
services:

    #
    # Repositories.
    #
    ccdn_component_attachment.repository.attachment:
        class: %ccdn_component_attachment.repository.attachment.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %ccdn_component_attachment.entity.attachment.class%

    ccdn_component_attachment.repository.registry:
        class: %ccdn_component_attachment.repository.registry.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %ccdn_component_attachment.entity.registry.class%

    #
    # Gateways.
    #
    ccdn_component_attachment.gateway_bag:
        class: %ccdn_component_attachment.gateway_bag.class%
        arguments: [@service_container]

    ccdn_component_attachment.gateway.attachment:
        class: %ccdn_component_attachment.gateway.attachment.class%
        arguments:
            - @doctrine
            - @ccdn_component_attachment.gateway_bag
            - %ccdn_component_attachment.entity.attachment.class%

    ccdn_component_attachment.gateway.registry:
        class: %ccdn_component_attachment.gateway.registry.class%
        arguments:
            - @doctrine
            - @ccdn_component_attachment.gateway_bag
            - %ccdn_component_attachment.entity.registry.class%

    #
    # Managers.
    #
    ccdn_component_attachment.manager_bag:
        class: %ccdn_component_attachment.manager_bag.class%
        arguments: [@service_container]

    ccdn_component_attachment.manager.attachment:
        class: %ccdn_component_attachment.manager.attachment.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_component_attachment.gateway.attachment
            - @ccdn_component_attachment.manager_bag

    ccdn_component_attachment.manager.registry:
        class: %ccdn_component_attachment.manager.registry.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_component_attachment.gateway.registry
            - @ccdn_component_attachment.manager_bag

    #
    # Attachment Forms.
    #
    ccdn_component_attachment.form.type.attachment_upload:
        class: %ccdn_component_attachment.form.type.attachment_upload.class%
        arguments: 
            - %ccdn_component_attachment.entity.attachment.class%

    ccdn_component_attachment.form.handler.attachment_upload:
        class: %ccdn_component_attachment.form.handler.attachment_upload.class%
        arguments:
            - @form.factory
            - @ccdn_component_attachment.form.type.attachment_upload
            - @ccdn_component_attachment.manager.attachment
            - @ccdn_component_attachment.component.helper.file_manager

    ccdn_component_attachment.form.validator.upload_quota_disk_space:
        class: %ccdn_component_attachment.form.validator.upload_quota_disk_space.class%
        arguments:
            - @ccdn_component_attachment.manager.attachment
            - @ccdn_component_common.component.helper.bin_si_units
        tags:
            - { name: validator.constraint_validator, alias: UploadQuotaDiskSpaceValidator }

    ccdn_component_attachment.form.validator.upload_quota_file_quantity:
        class: %ccdn_component_attachment.form.validator.upload_quota_file_quantity.class%
        arguments:
            - @ccdn_component_attachment.manager.attachment
            - @ccdn_component_common.component.helper.bin_si_units
        tags:
            - { name: validator.constraint_validator, alias: UploadQuotaFileQuantityValidator }

    ccdn_component_attachment.form.validator.upload_quota_file_size:
        class: %ccdn_component_attachment.form.validator.upload_quota_file_size.class%
        arguments:
            - @ccdn_component_attachment.manager.attachment
            - @ccdn_component_common.component.helper.bin_si_units
        tags:
            - { name: validator.constraint_validator, alias: UploadQuotaFileSizeValidator }

    #
    # Attachment File Resolver.
    #
    ccdn_component_attachment.component.helper.file_resolver:
        class: %ccdn_component_attachment.component.helper.file_resolver.class%
        arguments:
            - @service_container

    ccdn_component_attachment.component.helper.file_manager:
        class: %ccdn_component_attachment.component.helper.file_manager.class%
        arguments:
            - @ccdn_component_common.component.helper.bin_si_units
            - %ccdn_component_attachment.store.dir%

    ccdn_component_attachment.component.twig_extension.get_attachment_quotas:
        class: %ccdn_component_attachment.component.twig_extension.get_attachment_quotas.class%
        arguments:
            - @ccdn_component_attachment.manager.attachment
        tags:
            - { name: twig.extension }

    #
    # Dashboard Integrator.
    #
    ccdn_component_attachment.component.dashboard.integrator:
        class: %ccdn_component_attachment.component.dashboard.integrator.class%
        tags:
            - { name: ccdn_component_dashboard.integrator }

    #
    # Route Referer.
    #
    ccdn_component_attachment.component.route_referer_ignore.list:
        class: %ccdn_component_attachment.component.route_referer_ignore.list.class%
        tags:
            - { name: ccdn_user_security.route_referer_ignore }
