namespaces:
    CCDNComponentAttachmentBundle: CCDNComponent\AttachmentBundle\Form\Validator\Constraints\

%ccdn_component_attachment.entity.attachment.class%:
    constraints:
        - "CCDNComponentAttachmentBundle:UploadQuotaFileSize": { groups: [upload] }
        - "CCDNComponentAttachmentBundle:UploadQuotaDiskSpace": { groups: [upload] }
        - "CCDNComponentAttachmentBundle:UploadQuotaFileQuantity": { groups: [upload] }
    properties:
        description:
            - Type: { type: string, groups: [upload] }
            - MaxLength: { limit: 1000, groups: [upload] }
        attachment:
            - NotNull: { groups: [upload] }
            - File: { groups: [upload] }
