namespaces:
    CCDNComponentAttachmentBundle: CCDNComponent\AttachmentBundle\Form\Validator\Constraints\

CCDNComponent\AttachmentBundle\Entity\Attachment:
    constraints:
        - "CCDNComponentAttachmentBundle:UploadQuotaFileSize": { groups: [upload] }
        - "CCDNComponentAttachmentBundle:UploadQuotaDiskSpace": { groups: [upload] }
        - "CCDNComponentAttachmentBundle:UploadQuotaFileQuantity": { groups: [upload] }
    properties:
        description:
            - Type: { type: string, groups: [upload] }
        #    - NotBlank: { groups: [upload] }
        #    - MinLength: { limit: 5, groups: [upload] }
            - MaxLength: { limit: 1000, groups: [upload] }
        attachment:
            - NotNull: { groups: [upload] }
            - File: { groups: [upload] }
